# Generated by Django 5.2.6 on 2025-09-13 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_page_pcat_alter_page_pname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mypage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='ptcat',
            field=models.CharField(max_length=255, verbose_name='Page categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ptpublished',
            field=models.DateField(verbose_name='Page Published'),
        ),
    ]
