"""
Django settings for ch42 project.
Generated by 'django-admin startproject' using Django 5.2.5.
Docs:
- Deployment checklist: https://docs.djangoproject.com/en/5.2/howto/deployment/
- Settings ref: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# --- Paths -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security (dev defaults; change in production) ---------------------------
# ⚠️ Do NOT commit real secrets to Git. Use environment variables in prod.
SECRET_KEY = 'django-insecure-c@8r8nmfokf#q_bnpcvi7)d#qr4-ol989@#cprsaej=#my^t@s'
DEBUG = True
ALLOWED_HOSTS = []  # e.g. ['yourdomain.com'] in production

# --- Installed Apps ----------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',        # Auth framework (we override the user model)
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'customer',
    'seller',
    'account',
]

# --- Middleware --------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',              # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # attaches request.user
    'django.contrib.messages.middleware.MessageMiddleware',    # messages framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ch42.urls'

# --- Templates ---------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # If you add a global "templates" folder at project root, put it here.
        'DIRS': [],
        'APP_DIRS': True,  # auto-discover templates inside each app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ch42.wsgi.application'

# --- Database ----------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',      # Simple file DB for dev
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Password validation (Django’s built-ins) --------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# --- I18N / TZ ---------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static files ------------------------------------------------------------
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Custom User Model -------------------------------------------------------
# Tell Django to use our email-first user model
AUTH_USER_MODEL = 'account.User'

# --- Site meta used in emails & links ----------------------------------------
SITE_DOMAIN = 'http://127.0.0.1:8000/'  # local dev domain
SITE_NAME = 'Auth System'

# --- Email (Mailtrap SMTP) ---------------------------------------------------
# ⚠️ In production, use env vars for secrets.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'live.smtp.mailtrap.io'
EMAIL_HOST_USER = 'api'
EMAIL_HOST_PASSWORD = '21b5b11c16d665d4847fe6cb1141c06d'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# --- Auth redirects -----------------------------------------------------------
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# --- Password reset token expiry (seconds) -----------------------------------
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour
