# Generated by Django 5.2.6 on 2025-09-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('center_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candiate',
            fields=[
                ('exam_center_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.exam_center')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.IntegerField()),
            ],
            bases=('core.exam_center',),
        ),
    ]
