# Generated by Django 5.2.5 on 2025-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='hsp', max_length=70),
            preserve_default=False,
        ),
    ]
