# Generated by Django 5.2.5 on 2025-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(default='Here are simple comments', max_length=255),
        ),
    ]
